function getTimestamp(){return`[${(new Date).toISOString()}]`}var auto_extract_flag=!1,processing_flag=!1,leads=[],leads_lnglat=new Set;async function saveLeadsToStorage(){try{const a={leads,leads_lnglat:Array.from(leads_lnglat)};await chrome.storage.local.set({gmb_scraper_leads:a});console.log(getTimestamp(),"Leads saved to chrome storage:",leads.length)}catch(a){console.error(getTimestamp(),"Error saving leads to storage:",a)}}
async function loadLeadsFromStorage(){try{const a=await chrome.storage.local.get("gmb_scraper_leads");if(a.gmb_scraper_leads){const c=a.gmb_scraper_leads;leads=c.leads||[];leads_lnglat=new Set(c.leads_lnglat||[]);console.log(getTimestamp(),"Leads loaded from chrome storage:",leads.length)}}catch(a){console.error(getTimestamp(),"Error loading leads from storage:",a),leads=[],leads_lnglat=new Set}}
async function updateLeads(a){Array.isArray(a)?(a.forEach(c=>{c&&c.cid&&!leads_lnglat.has(c.cid)&&(c.profileURL=`https://www.google.com/maps?cid=${c.cid}`,leads_lnglat.add(c.cid),leads.push(c))}),await saveLeadsToStorage()):console.error(getTimestamp(),"updateLeads expects an array")}async function clearLeads(){leads=[];leads_lnglat.clear();await saveLeadsToStorage()}var auto_extract_review_flag=!1,processing_review_flag=!1,reviews=[],review_ids=new Set;
function renderLeadsUI(){var a=document.createElement("div");a.className="extension_gms_page";a.id="extension_gms_page";var c=document.createElement("span");c.id="extension_gms_leads_info";c.className="extension_gms_status";const b=document.createElement("button");b.className="extension_gms_button";b.innerText="Start Auto Extract";b.id="extension_gms_start_btn";b.addEventListener("click",async f=>{f=f.target;if(auto_extract_flag)f.innerText="Start Auto Extract",auto_extract_flag=!1,console.log(getTimestamp(),
"Begin to stop auto extract!");else{f.innerText="Stop Auto Extract";f.style="background-color: #ea4335";auto_extract_flag=!0;console.log(getTimestamp(),"Begin to start auto extract!");let g=null,h=0;for(;auto_extract_flag;){for(;processing_flag;)await new Promise(m=>setTimeout(m,1E3));console.log(getTimestamp(),"Paging!");let k=0,n=document.getElementById("pnnext");for(;!n&&3>k;)console.log(getTimestamp(),"No next page button found, retry times: ",k),await new Promise(m=>setTimeout(m,3E3)),n=document.getElementById("pnnext"),
k++;if(n)if(g===n){const m=1E3*Math.floor(10*Math.random()+10);await new Promise(q=>setTimeout(q,m));h+=m;if(6E4<h){console.log(getTimestamp(),"Loading time is too long, break!");break}}else g=n,h=0,n.click(),await new Promise(m=>setTimeout(m,1E3*Math.floor(10*Math.random()+10)));else{console.log(getTimestamp(),"No Next Page!");alert("Arrive at the Last Page!");break}}f.innerText="Start Auto Extract";f.style="";auto_extract_flag=!1;console.log(getTimestamp(),"Finish auto extract!")}});const e=document.createElement("button");
e.className="extension_gms_button";e.innerText=`Export Results(${leads.length})`;e.id="extension_gms_download_btn";e.style="background-color: #54aced";e.addEventListener("click",async()=>{chrome.runtime.sendMessage({action:"openPage",data:leads})});e.innerText=`Export Results(${leads.length})`;const d=document.createElement("button");d.className="extension_gms_button";d.innerText="Clear";d.id="extension_gms_clear_btn";d.style="background-color: #4167b2";d.addEventListener("click",async()=>{await clearLeads();
e.innerText=`Export Results(${leads.length})`});a.appendChild(c);a.appendChild(b);a.appendChild(e);a.appendChild(d);document.body&&!document.body.contains(a)&&(document.body.insertBefore(a,document.body.firstChild),document.getElementById("searchform").style.top="90px",console.log(getTimestamp(),"extension_gms_page inserted successfully"));setInterval(()=>{document.body&&!document.body.contains(a)&&(document.body.insertBefore(a,document.body.firstChild),document.getElementById("searchform").style.top=
"90px",console.log(getTimestamp(),"extension_gms_page inserted successfully"))},1E4)}
function renderReviewUI(){var a=document.createElement("div");a.className="extension_gms_page";a.style="background-color: #ccc;";var c=document.createElement("span");c.id="extension_review_info";c.className="extension_gms_status";const b=document.createElement("button");b.className="extension_gms_button";b.innerText="Start Auto Extract Review";b.id="extension_review_start_btn";b.addEventListener("click",async f=>{f=f.target;if(auto_extract_review_flag)f.innerText="Start Auto Extract Review",auto_extract_review_flag=
!1,console.log(getTimestamp(),"Begin to stop auto extract review!");else{var g=document.querySelectorAll("#reviews-panel");if(0>=g.length)alert("Click one result in the left listing and Open the Reviews panel first!");else if("block"!=window.getComputedStyle(g[g.length-1]).getPropertyValue("display"))alert("Click one result in the left listing and Open the Reviews panel first!");else{f.innerText="Stop Auto Extract Review";f.style="background-color: #ea4335";auto_extract_review_flag=!0;for(console.log(getTimestamp(),
"Begin to start auto extract review!");auto_extract_review_flag;){for(;processing_review_flag;)await new Promise(k=>setTimeout(k,1E3));console.log(getTimestamp(),"Paging!");g=reviews.length;let h=0;for(;3>h;){const k=document.querySelectorAll(".eyxqWe");(2<=k.length?k[k.length-2]:k[0]).scrollIntoView({behavior:"smooth",block:"end"});await new Promise(n=>setTimeout(n,1E3*Math.floor(6*Math.random()+6)));if(reviews.length>g)break;else h+=1}if(3<=h){console.log(getTimestamp(),"No Next Page!");alert("Arrive at the Last Page!");
break}}f.innerText="Start Auto Extract Review";f.style="";auto_extract_review_flag=!1;console.log(getTimestamp(),"Finish auto extract review!")}}});const e=document.createElement("button");e.className="extension_gms_button";e.innerText=`Export Review Results(${reviews.length})`;e.id="extension_review_download_btn";e.style="background-color: #54aced";e.addEventListener("click",async()=>{chrome.runtime.sendMessage({action:"openReviewPage",data:reviews})});const d=document.createElement("button");d.className=
"extension_gms_button";d.innerText="Clear";d.id="extension_review_clear_btn";d.style="background-color: #4167b2";d.addEventListener("click",async()=>{window.reviews=[];window.review_ids.clear();e.innerText=`Export Results(${reviews.length})`});a.appendChild(c);a.appendChild(b);a.appendChild(e);a.appendChild(d);document.body.insertBefore(a,document.body.firstChild)}
(()=>{"lcl"===(new URLSearchParams(window.location.search)).get("tbm")&&(renderLeadsUI(),(async()=>{await loadLeadsFromStorage();const a=document.getElementById("extension_gms_download_btn");a&&(a.innerText=`Export Results(${leads.length})`)})())})();
function parseBusinessData(a){let c={};try{if(a&&Array.isArray(a)&&3<a.length){const b=a[3];if(b&&Array.isArray(b)){a=null;6<b.length&&b[6]&&(a=b[6]);if(a&&"string"===typeof a){a.startsWith(")]}'\n")&&(a=a.substring(5));try{a=JSON.parse(a)}catch(e){return console.error(getTimestamp(),"Failed to parse details as JSON:",e),c}}if(a&&Array.isArray(a)){const e=a[6]?.[7]?.[0]||"",d=a[6]?.[11]||"",f=a[6]?.[9]?.[2]||"",g=a[6]?.[9]?.[3]||"",h=Array.isArray(a[6]?.[2])?a[6][2].join(","):"",k=a[6]?.[4]?.[8]||
"",n=a[6]?.[4]?.[7]||"",m=Array.isArray(a[6]?.[13])?a[6][13].join(","):"";c={name:d,phone:a[6]?.[178]?.[0]?.[0]||"",address:h,website:e,category:m,ratingCount:k,averageRating:n,latitude:f,longitude:g,kg_id:a[6]?.[227]?.[0]?.[3]||"",place_id:a[6]?.[227]?.[0]?.[4]||"",business_profile_id:a[6]?.[227]?.[0]?.[5]||"",cid:a[25]?.[3]?.[0]?.[13]?.[0]?.[0]?.[1]||"",reviewExample:a[6]?.[175]?.[9]?.[0]?.[0]?.[2]?.[0]?.[2]?.[15]?.[0]?.[0]||""};const q=a[6]?.[203]?.[0]||[],p="Monday Tuesday Wednesday Thursday Friday Saturday Sunday".split(" ");
p.forEach(r=>{c[r]=""});Array.isArray(q)&&q.forEach(r=>{var l=r?.[1];(l=l?p[l-1]:null)&&(c[l]=r?.[3]?.[0]?.[0]||"")})}}}}catch(b){console.error(getTimestamp(),"Failed to parse APP_INITIALIZATION_STATE structure:",b)}return c}
async function extractBusinessData(a){try{var c=["window.APP_INITIALIZATION_STATE","var APP_INITIALIZATION_STATE","APP_INITIALIZATION_STATE"],b=-1,e=null;for(var d of c)if(b=a.indexOf(d),-1!==b){e=d;break}if(-1!==b){var f=a.indexOf("=",b+e.length);if(-1!==f&&100>f-b){c=-1;for(b=f+1;b<f+50&&b<a.length;b++)if("["===a[b]){c=b;break}if(-1!==c){f=1;e=b=!1;d=null;let g=c+1;for(;g<a.length&&1E7>g-c&&0<f;){const h=a[g];e?e=!1:"\\"===h?e=!0:b||'"'!==h&&"'"!==h?b&&h===d?(b=!1,d=null):b||("["===h?f++:"]"===
h&&f--):(b=!0,d=h);g++}if(0===f){const h=a.substring(c,g);try{const k=JSON.parse(h);console.log(getTimestamp(),"Extracted APP_INITIALIZATION_STATE via manual bracket matching");return parseBusinessData(k)}catch(k){console.warn(getTimestamp(),"Manual extraction matched brackets but JSON parse failed:",k.message)}}else console.warn(getTimestamp(),"Manual extraction could not find matching bracket or exceeded safety limit")}}}}catch(g){console.warn(getTimestamp(),"Manual extraction error:",g.message)}console.log(getTimestamp(),
"Manual extraction failed, falling back to sandbox iframe...");return new Promise(async g=>{try{const h=chrome.runtime.getURL("sandbox.html"),k=document.createElement("iframe");k.style.display="none";k.src=h;const n="req_"+Date.now()+"_"+Math.random().toString(36).substring(2,9);let m,q,p;const r=()=>{m&&window.removeEventListener("message",m);p&&window.removeEventListener("message",p);q&&clearTimeout(q);k.parentNode&&document.body.removeChild(k)};q=setTimeout(()=>{r();console.error(getTimestamp(),
"Timeout: Sandbox took too long to respond for request",n);g({})},6E4);p=l=>{"sandboxReady"===l.data.action&&l.source===k.contentWindow&&(window.removeEventListener("message",p),p=null,k.contentWindow.postMessage({action:"extractAppState",requestId:n,html:a},"*"))};m=l=>{l.source===k.contentWindow&&"appStateExtracted"===l.data.action&&l.data.requestId===n&&(r(),l.data.success?(l=parseBusinessData(l.data.data),g(l)):(console.error(getTimestamp(),"Failed to extract APP_INITIALIZATION_STATE for request",
n,":",l.data.error),g({})))};window.addEventListener("message",p);window.addEventListener("message",m);document.body.appendChild(k)}catch(h){console.error(getTimestamp(),"Failed to extract business data:",h.message),g({})}})}
async function extractBusinessDataForCID(a,c){try{const b=await extractBusinessData(c);if(b&&!leads_lnglat.has(a)){try{if(b.website){document.getElementById("extension_gms_leads_info").innerHTML="Searching Emails for "+b.name+" ... ";const e=await chrome.runtime.sendMessage({action:"email",data:{website:b.website,name:b.name,deep_search:!0}});console.log(getTimestamp(),"social_links:",e);if(e)for(const d in e)b[d]=e[d].join(",")}}catch(e){console.warn(getTimestamp(),"collect email error: ",b,e)}return b}}catch(b){console.warn(getTimestamp(),
"extractBusinessDataForCID error: ",a,b)}return null}
function buildBrowserLikeHeaders(){const a={};var c=(Array.isArray(navigator.languages)&&0<navigator.languages.length?navigator.languages:[navigator.language||"en-US"]).map((b,e)=>0===e?b:`${b};q=${Math.max(.1,1-.1*e).toFixed(1)}`).join(", ");a["user-agent"]=navigator.userAgent;a.accept="text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8";a["accept-language"]=c;a["cache-control"]="max-age=0";a.pragma="no-cache";a["upgrade-insecure-requests"]="1";a["sec-fetch-dest"]=
"document";a["sec-fetch-mode"]="navigate";a["sec-fetch-site"]="none";a["sec-fetch-user"]="?1";a.referer=window.location.href;navigator.userAgentData&&(Array.isArray(navigator.userAgentData.brands)&&(c=navigator.userAgentData.brands.map(b=>`"${b.brand}";v="${b.version}"`).join(", "))&&(a["sec-ch-ua"]=c),"boolean"===typeof navigator.userAgentData.mobile&&(a["sec-ch-ua-mobile"]=navigator.userAgentData.mobile?"?1":"?0"),navigator.userAgentData.platform&&(a["sec-ch-ua-platform"]=`"${navigator.userAgentData.platform}"`));
return a}
async function getPlacePageData(a){try{if(leads_lnglat.has(a))return console.log(getTimestamp(),"Business data already extracted for CID: ",a),null;document.getElementById("extension_gms_leads_info").innerHTML="Fetching page data for place id: "+a;console.log(getTimestamp(),"Fetching page data for CID: ",a);const c=`${atob("aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS9tYXBzLw==")}?cid=${a}`;let b,e;for(let d=1;3>=d;d++){try{if(1<d){const g=1E3*(Math.floor(3*Math.random())+2);console.log(getTimestamp(),`[CONTENT] Waiting ${g/
1E3}s before attempt ${d}...`);await new Promise(h=>setTimeout(h,g))}console.log(getTimestamp(),`[CONTENT] Attempt ${d}: Sending fetch request to background`);const f={userAgent:navigator.userAgent,referer:window.location.href,language:navigator.language||"en-US",headers:buildBrowserLikeHeaders()};b=await chrome.runtime.sendMessage({action:"fetchWithSorryDetection",url:c,cid:a,timeout:3E4,browserContext:f});console.log(getTimestamp(),"[CONTENT] Fetch result:",b);if(b.needsVerification)if(console.warn(getTimestamp(),
"[CONTENT] Google anti-bot verification required"),b.verificationComplete){console.log(getTimestamp(),"[CONTENT] \u2713 Verification completed automatically");const g=1E3*(Math.floor(31*Math.random())+30);console.log(getTimestamp(),`[CONTENT] Sleeping for ${g/1E3}s to avoid re-triggering anti-bot...`);document.getElementById("extension_gms_leads_info").innerHTML=`Verification complete! Waiting ${Math.floor(g/1E3)}s before continuing...`;await new Promise(h=>setTimeout(h,g));console.log(getTimestamp(),
"[CONTENT] Resuming after verification cooldown");document.getElementById("extension_gms_leads_info").innerHTML="Resuming data collection...";continue}else return b.userCanceled?(console.warn(getTimestamp(),"[CONTENT] User canceled verification, skipping this item and continuing..."),document.getElementById("extension_gms_leads_info").innerHTML="Verification canceled. Continuing..."):b.timeout?(console.warn(getTimestamp(),"[CONTENT] Verification timeout (1 minute), skipping this item and continuing..."),
document.getElementById("extension_gms_leads_info").innerHTML="Verification timeout. Continuing..."):(console.warn(getTimestamp(),"[CONTENT] Verification needed but status unclear, skipping..."),document.getElementById("extension_gms_leads_info").innerHTML="Verification issue. Continuing..."),null;if(b.success)return console.log(getTimestamp(),`[CONTENT] Successfully fetched ${b.data.length} bytes`),b.data;console.warn(getTimestamp(),`[CONTENT] Fetch failed: ${b.error}`);e=Error(b.error)}catch(f){console.error(getTimestamp(),
"[CONTENT] Exception during fetch:",f),e=f}if(3>d)if(b&&b.error&&b.error.includes("429")){const f=1E3*Math.floor(60*Math.random()+3);console.log(getTimestamp(),`Rate limited, sleeping for ${f/1E3}s before retry`);await new Promise(g=>setTimeout(g,f))}else{const f=1E3*Math.floor(2*Math.random()+1);console.log(getTimestamp(),`Error occurred, sleeping for ${f/1E3}s before retry`);await new Promise(g=>setTimeout(g,f))}}throw e||Error("Failed to fetch url after 3 attempts");}catch(c){console.warn(getTimestamp(),
"getPlacePageData error: ",a,c)}return null}let messageQueue=Promise.resolve(),seen_cids=new Set;
async function handleSearchMessage(a){try{console.log(getTimestamp(),"Handle new search message received. Content length: ",a.length);processing_flag=!0;var c=[...a.matchAll(/data-cid="([^"]*)"/g)].map(d=>d[1]).filter(d=>{if(seen_cids.has(d)||leads_lnglat.has(d))return!1;seen_cids.add(d);return!0});console.debug(getTimestamp(),"Found CIDs:",c);console.debug(getTimestamp(),`\nTotal: ${c.length} CIDs found`);a=[];for(var b of c){const d=await getPlacePageData(b);d&&a.push({cid:b,data:d});const f=1E3*
Math.floor(3*Math.random());await new Promise(g=>setTimeout(g,f))}c=[];for(b=0;b<a.length;b+=10){const d=a.slice(b,b+10).map(g=>extractBusinessDataForCID(g.cid,g.data)),f=await Promise.all(d);c.push(...f)}console.debug(getTimestamp(),c);const e=c.filter(d=>d&&d.cid);await updateLeads(e);document.getElementById("extension_gms_download_btn").innerText=`Export Results(${leads.length})`;document.getElementById("extension_gms_leads_info").innerHTML="";processing_flag=!1}catch(e){console.warn(getTimestamp(),
e)}finally{processing_flag=!1}}window.addEventListener("message",async function(a){if("search"==a.data.type){console.log(getTimestamp(),"Search message received. Type: ",a.data.type,"Content length: ",a.data.data.length);const c=a.data.data;messageQueue=messageQueue.then(()=>handleSearchMessage(c))}});(()=>{if("lcl"===(new URLSearchParams(window.location.search)).get("tbm")){const a=document.getElementById("main").outerHTML;window.postMessage({type:"search",data:a},"*")}})();
